[DA-166] Setup spotless

diff --git a/scripts/pre-commit/pre-commit b/scripts/pre-commit/pre-commit
--- a/scripts/pre-commit/pre-commit
+++ b/scripts/pre-commit/pre-commit
@@ -1,4 +1,21 @@
 #!/usr/bin/env bash
+echo "Running spotless check..."
+OUTPUT="/tmp/spotless-$(date +%s)"
+./gradlew spotlessCheck > $OUTPUT
+EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  cat $OUTPUT
+  rm $OUTPUT
+  echo "***********************************************"
+  echo "                spotless failed                "
+  echo "   Run './gradlew spotlessApply' to fix it     "
+  echo "***********************************************"
+  exit $EXIT_CODE
+fi
+rm $OUTPUT
+
+echo "spotless check is success"
+
 echo "Running detekt check..."
 OUTPUT="/tmp/detekt-$(date +%s)"
 ./gradlew detekt > $OUTPUT
